####################################################
###                                              ###
###              LOADING MAPPINGS                ###
###                                              ###
####################################################


[mappings]

coarsness		= "fine" # fine, coarse
basename_left 		= "Mapping"
basename_right		= "sphere"
mesh_initialisation     = "morphed_sphere" #lung, morphed_sphere

####################################################
###                                              ###
###              RANGE OF STUDY          	 ###
###                                              ###
####################################################

[range]

lungs			= ["RL", "LL"]
